In [31]:
#q1 A)

In [24]:
import numpy as np
a=np.array([1,2,3,4,5])
n=len(a)
rev=a[-1:-n-1:-1]
print("Reverse Matrix")
print(rev)

Reverse Matrix
[5 4 3 2 1]


In [43]:
#q1 2 a)

In [26]:
import numpy as np
a=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
b=a.flatten()
print(b)

[1 2 3 2 4 5 1 2 3]


In [ ]:
#q1 2 b)

In [4]:
import numpy as np
a=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
b=a.ravel()
print(b)

[1 2 3 2 4 5 1 2 3]


In [ ]:
#q1 3

In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1==arr2)


[[ True  True]
 [ True  True]]


In [ ]:
#q1 4 a)

In [7]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)

Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]


In [ ]:
#q1 4 b)

In [8]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]
print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)

Most frequent value: 1
Indices of the most frequent value: [0 1 2]


In [ ]:
# q1 5 a)

In [9]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())

45


In [ ]:
# q1 5 b)

In [10]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg,axis=0))

[[20  9 16]]


In [ ]:
# q1 5 c)

In [11]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg,axis=1))

[[14]
 [16]
 [15]]


In [ ]:
#q1 6 a)

In [25]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(n_array.trace())

176


In [ ]:
#q1 6 b) & c)

In [12]:
import numpy as np
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues of n_array:")
print(eigenvalues)
print("Eigenvectors of n_array:")
print(eigenvectors)


Eigenvalues of n_array:
[98.16835147 28.097044   49.73460452]
Eigenvectors of n_array:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
#q1 6 d)

In [13]:
import numpy as np
n = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print(np.linalg.inv(n))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
#q1 6 e)

In [14]:
import numpy as np
n = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print(np.linalg.det(n))

137180.0000000001


In [ ]:
#q1 7 a)

In [29]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = p @ q
print(product)
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
p_flattened = p.flatten()
q_flattened = q.flatten()
mean_p = np.mean(p_flattened)
mean_q = np.mean(q_flattened)
covariance = np.mean((p_flattened - mean_p) * (q_flattened - mean_q))
print('Covariance =',covariance)

[[16 19]
 [26 31]]
Covariance = 0.75


In [ ]:
#q1 7 b)

In [30]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product = p @ q
print("Matrix multiplication result:")
print(product)
p_flattened = p.flatten()
q_flattened = q.flatten()
mean_p = np.mean(p_flattened)
mean_q = np.mean(q_flattened)
covariance = np.mean((p_flattened - mean_p) * (q_flattened - mean_q))
print('Covariance =',covariance)

Matrix multiplication result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance = 0.19444444444444464


In [ ]:
#q1 8

In [34]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.dot(x,y.T) 
print('******Inner_product*******')
print(inner_product)
x_flattened = x.flatten()
y_flattened = y.flatten()
outer_product = np.outer(x_flattened, y_flattened)
print('******Outer_product*******')
print(outer_product)
xx, yy = np.meshgrid(x_flattened, y_flattened, indexing='ij')
cartesian_product = np.vstack([xx.ravel(), yy.ravel()]).T
print('******Cartesian_product*******')
print(cartesian_product)

******Inner_product*******
[[17 52]
 [13 62]]
******Outer_product*******
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
******Cartesian_product*******
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
#q2

In [ ]:
# a 1

In [35]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
absolute_array = np.abs(array)
print("Element-wise absolute value:\n", absolute_array)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# a 2

In [37]:
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
print("25th, 50th, 75th percentiles of flattened array:", percentiles_flattened)
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("25th, 50th, 75th percentiles for each column:\n", percentiles_columns)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("25th, 50th, 75th percentiles for each row:\n", percentiles_rows)

25th, 50th, 75th percentiles of flattened array: [-3.5 -0.5  2.5]
25th, 50th, 75th percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25th, 50th, 75th percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
# a 3

In [38]:
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

print("Mean of flattened array:", mean_flattened)
print("Median of flattened array:", median_flattened)
print("Standard Deviation of flattened array:", std_flattened)
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

print("Mean for each column:", mean_columns)
print("Median for each column:", median_columns)
print("Standard Deviation for each column:", std_columns)
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Mean for each row:", mean_rows)
print("Median for each row:", median_rows)
print("Standard Deviation for each row:", std_rows)


Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224
Mean for each column: [-1.5  1.5 -1.5]
Median for each column: [-1.5  1.5 -1.5]
Standard Deviation for each column: [2.5 3.5 4.5]
Mean for each row: [ 0.66666667 -1.66666667]
Median for each row: [ 1. -4.]
Standard Deviation for each row: [2.05480467 4.78423336]


In [ ]:
# b

In [40]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
# 3 a 1

In [41]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of the sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_elements = np.sort(array)[:4]

# iv. 5 largest elements
largest_elements = np.sort(array)[-5:]

print("Original array:", array)
print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)


Original array: [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [ ]:
# 3 b 

In [42]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# Integer elements only
integer_elements = array[array == array.astype(int)]

# Float elements only
float_elements = array[array != array.astype(int)]

print("Original array:", array)
print("Integer elements only:", integer_elements)
print("Float elements only:", float_elements)


Original array: [1.  1.2 2.2 2.  3.  2. ]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [ ]:
# 4 